# fly.toml file generated for eloco-dns on 2022-06-07T14:18:05+08:00

app = "eloco-dns"

kill_signal = "SIGTERM"
kill_timeout = 120

[[services]]
  internal_port = 53
  protocol = "udp"

  [services.concurrency]
    hard_limit = 550
    soft_limit = 500
    type = "connections"

  [[services.ports]]
    port = 53
