# fly.toml file generated for eloco-dns-oversea on 2022-06-08T10:26:19+08:00

app = "eloco-dns-oversea"

kill_signal = "SIGTERM"
kill_timeout = 120

[[services]]
  internal_port = 2053
  protocol = "udp"

  [services.concurrency]
    hard_limit = 55
    soft_limit = 50
    type = "connections"

  [[services.ports]]
    port = 53
