# fly.toml file generated for eloco-dns-test on 2022-06-07T22:47:26+08:00

app = "eloco-dns-test"

kill_signal = "SIGTERM"
kill_timeout = 120

[[services]]
  internal_port = 2053
  protocol = "udp"

  [services.concurrency]
    hard_limit = 55
    soft_limit = 50
    type = "connections"

  [[services.ports]]
    port = 2053
